# Generated by Django 4.1.5 on 2023-04-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_text_alter_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='question',
            name='thumbnailA1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像1 (正解)'),
        ),
        migrations.AddField(
            model_name='question',
            name='thumbnailA2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像2 (正解)'),
        ),
        migrations.AddField(
            model_name='question',
            name='thumbnailA3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像3 (正解)'),
        ),
        migrations.AddField(
            model_name='question',
            name='thumbnailQ1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像1 (問題)'),
        ),
        migrations.AddField(
            model_name='question',
            name='thumbnailQ2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像2 (問題)'),
        ),
        migrations.AddField(
            model_name='question',
            name='thumbnailQ3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像3 (問題)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(verbose_name='問題'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(verbose_name='問題'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(verbose_name='問題'),
        ),
        migrations.AlterField(
            model_name='question',
            name='wronganswer1',
            field=models.TextField(verbose_name='問題'),
        ),
        migrations.AlterField(
            model_name='question',
            name='wronganswer2',
            field=models.TextField(verbose_name='問題'),
        ),
        migrations.AlterField(
            model_name='question',
            name='wronganswer3',
            field=models.TextField(verbose_name='問題'),
        ),
    ]
