# Generated by Django 4.1.5 on 2023-04-14 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_question_thumbnail_question_thumbnaila1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint1',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='ヒント1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='hint2',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='ヒント2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(verbose_name='正解'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='question',
            name='wronganswer1',
            field=models.TextField(verbose_name='誤回答1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='wronganswer2',
            field=models.TextField(verbose_name='誤回答2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='wronganswer3',
            field=models.TextField(verbose_name='誤回答3'),
        ),
    ]
