# Generated by Django 4.1.5 on 2023-04-15 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0004_question_hint1_question_hint2_alter_question_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('JAVA', 'JAVA'), ('Linux', 'Linux'), ('LinuC1', 'LinuC1'), ('LPIC1', 'LPIC1'), ('G検定', 'G検定'), ('Python(全般)', 'Python(All)'), ('Python(Django)', 'Python(Django)'), ('Python(Machine Learning)', 'Python(機械学習)'), ('Python(Pandas)', 'Python(Pandas)'), ('Python3エンジニア認定基礎試験', 'Python3エンジニア認定基礎試験'), ('Python3エンジニア認定データ分析試験', 'Python3エンジニア認定データ分析試験'), ('Javascript(All)', 'Javascript(全般)'), ('Javascript(Vue.js)', 'Javascript(vue.js)'), ('DATA SCIENTIST', 'データ\u3000サイエンティスト'), ('DATABASE SPECIALIST', 'データベース\u3000スペシャリスト'), ('Bronze 12c SQL基礎', 'Bronze 12c SQL基礎'), ('NETWORK SPECIALIST', 'ネットワークスペシャリスト'), ('AP', '応用情報技術者試験'), ('FE', '基本情報技術者試験'), ('情報セキュリティマネジメント', '情報セキュリティマネジメント'), ('PHP', 'PHP'), ('SEO検定', 'SEO検定'), ('Access VBA', 'Access VBA'), ('Excel VBA', 'Excel VBA'), ('統計検定2級', '統計検定2級'), ('statistics', '統計学'), ('簿記2級', '簿記2級'), ('trivia', '雑学'), ('other', 'その他')], max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(null=True, verbose_name='解説'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint1',
            field=models.TextField(null=True, verbose_name='ヒント1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint2',
            field=models.TextField(null=True, verbose_name='ヒント2'),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('thumbnail1', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumbnail2', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumbnail3', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumbnail4', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumbnail5', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(choices=[('Excel VBA', 'Excel VBA'), ('other', 'その他')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
