# Generated by Django 4.1.5 on 2023-04-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_picturecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturecomment',
            name='category',
            field=models.CharField(choices=[('laugher', '笑い'), ('impressed', '感動'), ('other', 'その他')], max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('Excel VBA', 'Excel VBA'), ('LINE stickers', 'LINEスタンプ'), ('other', 'その他')], max_length=100),
        ),
    ]
