# Generated by Django 4.1.5 on 2023-04-17 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_category_alter_book_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='wronganswer4',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='誤回答4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='wronganswer5',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='誤回答5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='wronganswer6',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='誤回答6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='wronganswer7',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='誤回答7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='wronganswer8',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='誤回答8'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='wronganswer9',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='誤回答9'),
            preserve_default=False,
        ),
    ]
