# Generated by Django 4.1.5 on 2023-04-18 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_question_wronganswer4_question_wronganswer5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='shoseki',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='書籍'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='wronganswer4',
            field=models.TextField(blank=True, null=True, verbose_name='誤回答4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='wronganswer5',
            field=models.TextField(blank=True, null=True, verbose_name='誤回答5'),
        ),
        migrations.AlterField(
            model_name='question',
            name='wronganswer6',
            field=models.TextField(blank=True, null=True, verbose_name='誤回答6'),
        ),
        migrations.AlterField(
            model_name='question',
            name='wronganswer7',
            field=models.TextField(blank=True, null=True, verbose_name='誤回答7'),
        ),
        migrations.AlterField(
            model_name='question',
            name='wronganswer8',
            field=models.TextField(blank=True, null=True, verbose_name='誤回答8'),
        ),
        migrations.AlterField(
            model_name='question',
            name='wronganswer9',
            field=models.TextField(blank=True, null=True, verbose_name='誤回答9'),
        ),
    ]
