# Generated by Django 4.1.5 on 2023-04-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_question_shoseki_alter_question_wronganswer4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='shoseki',
            field=models.CharField(blank=True, choices=[('応用情報技術者\u3000試験によくでる問題集【午後】', '応用情報技術者\u3000試験によくでる問題集【午後】'), ('LINUC教科書LINUCレベル1スピードマスター問題集 VERSION10.0対応', 'LINUC教科書LINUCレベル1スピードマスター問題集 VERSION10.0対応'), ('Python3エンジニア認定基礎試験問題集', 'Python3エンジニア認定基礎試験問題集'), ('データベーススペシャリスト教科書令和4年度', 'データベーススペシャリスト教科書令和4年度'), ('Bronze 12c SQL 基礎問題集', 'Bronze 12c SQL 基礎問題集'), ('シェルワンライナー100本ノック', 'シェルワンライナー100本ノック'), ('Access VBA スタンダード', 'Access VBA スタンダード'), ('Access VBA ベーシック', 'Access VBA ベーシック'), ('Excel VBA スタンダード', 'Excel VBA スタンダード'), ('Excel VBA ベーシック', 'Excel VBA ベーシック'), ('基本情報技術者らくらく突破 Python', '基本情報技術者らくらく突破 Python'), ('情報セキュリティマネジメント教科書令和2年度', '情報セキュリティマネジメント教科書令和2年度'), ('LPICレベル1スピードマスター問題集', 'LPICレベル1スピードマスター問題集'), ('ディープラーニングG検定ジェネラリスト要点整理テキスト&問題集', 'ディープラーニングG検定ジェネラリスト要点整理テキスト&問題集')], max_length=100, null=True, verbose_name='書籍'),
        ),
    ]
