# Generated by Django 4.1.5 on 2023-04-21 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0011_alter_question_shoseki'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codememo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='内容')),
                ('category', models.CharField(choices=[('JAVA', 'JAVA'), ('Python', 'Python'), ('Jsvascript', 'Javascript'), ('PHP', 'PHP'), ('HTML,CSS', 'HTML,CSS'), ('SQL', 'SQL'), ('Excel VBA', 'Excel VBA'), ('Access VBA', 'Access VBA'), ('other', 'その他')], max_length=100, verbose_name='カテゴリ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
