# Generated by Django 4.1.5 on 2023-04-30 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_alter_question_category_alter_question_shoseki'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='shoseki_page',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
