# Generated by Django 4.1.5 on 2023-04-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_question_shoseki_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='shoseki_page',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
