# Generated by Django 4.2 on 2023-05-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_alter_question_shoseki_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='shoseki_page',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='書籍ページ'),
        ),
    ]
